apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-deployment
  labels:
    app: authentication-app
spec:
  replicas: 3  # Define the number of replicas for your deployment
  selector:
    matchLabels:
      app: authentication-app
  template:
    metadata:
      labels:
        app: authentication-app
    spec:
      containers:
        - name: authentication-app
          image: soffoalbert/content-manager:authentication-service  # Replace with your Docker image
          ports:
            - containerPort: 3001  # Replace with the port your NestJS app is configured to listen on
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health  # replace with your NestJS app's health check endpoint
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health  # replace with your NestJS app's health check endpoint
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 20
