apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-manager-bff-deployment
  labels:
    app: content-manager-bff
spec:
  replicas: 2
  selector:
    matchLabels:
      app: content-manager-bff
  template:
    metadata:
      labels:
        app: content-manager-bff
    spec:
      containers:
        - name: content-manager-bff
          image: soffoalbert/content-manager:content-manager-bff-v1
          ports:
            - containerPort: 3000  
          # resources:
          #   requests:
          #     memory: "1Gi"
          #     cpu: "1"
          #   limits:
          #     memory: "1Gi"
          #     cpu: "1"
          readinessProbe:
            httpGet:
              path: /admin/health  
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /admin/health  
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
