apiVersion: v1
kind: Service
metadata:
  name: authentication
  labels:
    app: content-manager
    service: authentication
spec:
  selector:
    app: content-manager
    service: authentication
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
